language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source
  
before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: 
  - ./vendor/bin/php-cs-fixer fix --verbose
  - ./vendor/bin/phpunit

notifications:
  
  email: "melitor@gmail.com"

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:
    
matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master